on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v1
    - name: Install GitVersion
      uses: ./setup
      with:
        versionSpec: '5.1.x'
